influxdata/clockface

- src/Components/Page/Page.scss
Closes #185 
Add missing prefix to restore padding around page content
Before
After
> Add missing prefix to restore padding around page content

- CHANGELOG.md
- package.json
Sync repo version to botched npm publish
> Bump version to match npm

- publish
Updates the `./publish` script to run a few checks before publishing:
- On the master branch
- master branch is even with origin/master
- The working tree is clean
This should prevent some issues with publish that Daniel and I worked through this morning.
> Update publish script

- CHANGELOG.md
- src/Components/Button/Base/ButtonBase.tsx
- src/Components/Button/Button.stories.tsx
- src/Components/Button/Composed/Button.tsx
- src/Components/Button/Composed/ConfirmationButton.md
- src/Components/Button/Composed/ConfirmationButton.scss
- src/Components/Button/Composed/ConfirmationButton.tsx
- src/Components/Button/Composed/SquareButton.tsx
- src/Components/Popover/Popover.scss
- src/Components/Popover/Popover.tsx
- src/Types/index.tsx
Closes #172
Rather than porting the component of the same name as defined in InfluxDB, I have recreated the functionality using a combination of `Button` and `Popover`.
- Combine `Button` and `Popover` into a composed button called `ConfirmationButton`
- Offers more customizability than the existing `ConfirmationButton`
- Port over the `Omit` typescript interface from InfluxDB (mimics the omit feature in the latest ts)
> feat: Introduce ConfirmationButton

- .storybook/Story.scss
- CHANGELOG.md
- src/Components/NavMenu/NavMenu.md
- src/Components/NavMenu/NavMenu.stories.tsx
- src/Components/NavMenu/NavMenuItem.md
- src/Components/NavMenu/NavMenuItem.tsx
- src/Components/NavMenu/NavMenuSubItem.md
Closes #145
- Add markdown documentation for all `NavMenu` components
> docs: add markdown docs for NavMenu components

- CHANGELOG.md
- src/Components/Popover/Popover.md
- src/Components/Popover/Popover.scss
- src/Components/Popover/Popover.stories.tsx
- src/Components/Popover/Popover.tsx
- src/Components/Popover/TextPopover.md
- src/Components/Popover/TextPopover.scss
- src/Components/Popover/TextPopover.tsx
Closes #250 
Closes #249 
- Make `Popover` type `outline` by default
- Introduce `TextPopover` as a composed version of `Popover` that doesn't require any customization
- Improve documentation for `Popover`
- Allow internal `Popover` state to be overridden externally
- Rename prop `initiallyVisible` to `visible`
> refactor: upgrade popovers

- .storybook/Story.scss
- CHANGELOG.md
- src/Components/AppWrapper/AppWrapper.scss
- src/Components/AppWrapper/AppWrapper.tsx
- src/Components/NavMenu/NavMenu.stories.tsx
- src/Components/NavMenu/NavMenu.tsx
- src/Components/Page/FullPage.md
- src/Components/Page/Page.md
- src/Components/Page/Page.scss
- src/Components/Page/Page.tsx
- src/Components/Page/PageContents.md
- src/Components/Page/PageContents.tsx
- src/Components/Page/PageHeader.md
- src/Components/Page/PageHeader.tsx
- src/Components/Page/PageTitle.md
- src/Components/Page/page.stories.tsx
Closes #253 
Closes #147 
- Fix styles such that `PageHeader` and `PageContents` margins line up vertically
- Simplify and consolidate styles between `PageHeader` and `PageContents`
- Add markdown documentation for `Page` components
- Improve how presentation mode is handled between `Page`, `AppWrapper`, and `NavMenu` (*Breaking*)
> feat: upgrade page components

- CHANGELOG.md
- src/Components/DapperScrollbars/DapperScrollbars.stories.tsx
- src/Components/DapperScrollbars/DapperScrollbars.tsx
- src/Components/Dropdowns/Composed/MultiSelectDropdown.tsx
- src/Components/Dropdowns/Composed/SelectDropdown.tsx
- src/Components/Dropdowns/Dropdown.stories.tsx
- src/Components/Dropdowns/Family/DropdownMenu.tsx
Closes #110
- Expose `scrollTop` & `scrollLeft` props on `DapperScrollbars
- Add `scrollToSelected` prop to `DropdownMenu`
- Add default behavior to scroll to selected item when dropdown menu is opened
> Scroll to selected when DropdownMenu is opened

- CHANGELOG.md
- src/Components/Form/Form.stories.tsx
- src/Components/Panel/Panel.scss
- src/Components/Panel/Panel.stories.tsx
- src/Components/Panel/Panel.tsx
- src/Components/Panel/PanelBody.tsx
- src/Components/Panel/PanelFooter.tsx
- src/Components/Panel/PanelHeader.tsx
- src/Components/Panel/PanelTitle.tsx
Closes #247
- _**BREAKING**_ Remove `size` prop from `Panel`
- Add `size` prop to `PanelHeader`, `PanelBody`, `PanelFooter,` and `PanelTitle`
- Use `DismissButton` component instead of custom dismiss button
> refactor: make all panel sub-components independently size-able

- CHANGELOG.md
- package.json
- rollup.config.js
- yarn.lock
Closes #279
Add Include Paths Rollup Plugin to handle unresolved paths.
> Add rollup-plugin-includepaths

- CHANGELOG.md
- src/Components/Popover/Base/Popover.tsx
- src/Components/Popover/Base/PopoverDialog.tsx
- src/Components/Popover/Documentation/Popover.stories.tsx
- src/Utils/index.ts
Closes #326 
- Remove `<span />` wrapping chil in `Popover`
- Popover `ref` prop passes through to "contents" element within `PopoverDialog`
- Use `useRef` instead of `createRef`
- Add popover to storybook examples that is visible by default (for testing purposes)
- Extract `createPortal` and `destroyPortal` functions into `/utils`
- Fire `handleUpdateStyles` on `PopoverDialog` initial render
Tested all changes in `influxdata/influxdb`
> fix: popover visibility

- CHANGELOG.md
- src/Components/SelectableCard/Documentation/SelectableCard.stories.tsx
- src/Components/SelectableCard/SelectableCard.scss
Closes #330 
- Make `inactive` and `disabled` slightly brighter so they don't blend into `Panel` default color
- Make `inactive` image state not greyed out or lower opacity
- Ensure story has all permutations visible at once (for testing purposes)
- Ensure the label truncates with `...` when it is too long
> Improve SelectableCard affordance

- src/Components/ColorPicker/ColorPicker.tsx
Closes #322, influxdata/influxdb#15311
Just a very little css fix for the color preview that was hiding the first two characters of the entered text input.
> Fix input padding in color picker component

- src/Components/ColorPicker/ColorPicker.scss
- src/Components/ColorPicker/ColorPicker.tsx
- src/Components/ColorPicker/Documentation/ColorPicker.stories.tsx
- src/Utils/hexCodeValidation.ts
Fixes some oversight from #340 
- Include `8` in list of accepted hexcode characters
- Send validation status of input event value not stale value
- This prevents the problem of the picker always returning `error`
- Allow for optional control over input value cleaning before it is passed in to `onChange`
- By default this blocks the user from typing invalid hexcode characters
> Fix Color Picker Bugs

- CHANGELOG.md
- src/Components/Popover/Base/Popover.tsx
Closes #15565
https://github.com/influxdata/influxdb/issues/15565
Added explicit checks to the Popover `handleTriggerMouseLeave` method to prevent period errors
N/A
> fix(popover): added explicit checks to resolve honeybadger issue

- CHANGELOG.md
- src/Components/Inputs/Documentation/Inputs.stories.tsx
- src/Components/Inputs/Documentation/TextArea.md
- src/Components/Inputs/Input.scss
- src/Components/Inputs/Input.tsx
- src/Components/Inputs/StatusIndicator.scss
- src/Components/Inputs/StatusIndicator.tsx
- src/Components/Inputs/TextArea.scss
- src/Components/Inputs/TextArea.tsx
- src/Styles/variables.scss
- src/Types/index.tsx
Closes #351 
Closes #143
- Extract out `StatusIndicator` from `Input` so it can be used in both `Input` and `TextArea`
- Create a set of "input" style variables that both `Input` and `TextArea` can share
- Ensure `TextArea` is making use of its `Size` prop
- Redesign error state to be more muted when not focused
- Redesign hover state to have greater contrast
- Fixes a bit (indirectly) that was causing `TextArea` to have a the same fixed height as `Input`
> Refactor TextArea

- package.json
- yarn.lock
Added `rollup-plugin-ts` then ran `yarn build`
```bash
yarn install
npm pack
ls -lh influxdata-clockface-1.0.2.tgz
yarn add $path_to_influxdata-clockface-1.0.2.tgz
yarn start
```
> build: add rollup-plugin-ts to get builds working with ts again

- CHANGELOG.md
- src/Components/Button/Composed/ConfirmationButton.tsx
- src/Components/Overlay/Documentation/Overlay.stories.tsx
- src/Components/Overlay/OverlayHeader.tsx
- src/Components/Popover/Documentation/Popover.stories.tsx
Closes #361 
Closes #349 
- Rearranged `OverlayHeader` so that the dismiss button is always the last element
- Add `PopoverStyle` and `PopoverClassName` props to `ConfirmationButton`
> Fix OverlayHeader and ConfirmationButton bugs

- CHANGELOG.md
- src/Components/Popover/Base/Popover.tsx
- src/Components/Popover/Base/PopoverDialog.tsx
Closes #367 
- Pass `visible` prop into `PopoverDialog` and prevent the intersection hide from firing if `visible` is true
> Fix Popover hide bug

- CHANGELOG.md
- src/Components/Inputs/Documentation/Inputs.stories.tsx
- src/Components/Inputs/Input.tsx
Closes https://github.com/influxdata/influxdb/issues/15024
Updates numeric Input to handle NaN appropriately.
> fix: handle NaN appropriately with value, type, and status

- CHANGELOG.md
- src/Components/Button/Base/ButtonBase.tsx
- src/Components/Button/Composed/Button.tsx
- src/Components/Button/Composed/ConfirmationButton.tsx
- src/Components/Button/Composed/DismissButton.tsx
- src/Components/Button/Composed/SquareButton.tsx
Closes #374 
Aiming to tighten the button component set a bit. This change enables button base changes to trickle down into the composed button components, which should make maintenance easier.
- Add `onMouseOut`, `onMouseOver`, `onMouseLeave`, and `onMouseEnter` to `BaseButtonProps`
- Ensure that `Button`, `DismissButton`, `SquareButton`, and `ConfirmationButton`'s props interfaces are extending `BaseButtonProps`
> Improve Button components

- .storybook/Story.scss
- src/Constants/colors.ts
- src/Types/Types.stories.tsx
- src/Types/index.tsx
- Use CSS grid to layout color and gradient swatches
- Able to fit 8 columns on a laptop screen
- Use better means of determining contrasting swatch label color
- Separate colors and gradients into individual spectrums
> Update design of color & gradient documentation

- CHANGELOG.md
- src/Components/Table/Documentation/Table.stories.tsx
- src/Components/Table/TableCell.tsx
- src/Components/Table/TableHeaderCell.tsx
Closes #401
- Remove "width" prop from `TableCell` and `TableHeaderCell`
- html5 no longer supports the "width" attribute on `<td>` and `<th>` elements and suggests using inline styles instead
> Remove "width" prop from TableCell and TableHeaderCell

- CHANGELOG.md
- src/Components/Button/Documentation/SquareButton.md
- src/Components/Dropdowns/DropdownMenu.tsx
Closes #404
Closes #257 
- Bind the `onHide` function to the contents of the menu rather than the wrapper
- Fix typo in `SquareButton` documentation
> Prevent dropdowns from dismissing when scrollbar is clicked

- CHANGELOG.md
- src/Components/Button/Composed/CTAButton.scss
- src/Components/FunnelPage/Documentation/ExampleFunnelPage.md
- src/Components/FunnelPage/Documentation/FunnelPage.md
- src/Components/FunnelPage/Documentation/FunnelPage.stories.tsx
- src/Components/FunnelPage/Family/FunnelPage.scss
- src/Components/Panel/Composed/PanelSymbolHeader.scss
Goal 1: Make funnel pages look more like the mockups
Goal 2: Decouple semantics from aesthetics
- Create CSS classes specifically for typography elements featured in the mockups
- These ensure visual consistency independently of what HTML element is used
- Make `CTAButton` match font size and height as specified in the mockups
- Adjust horizontal padding of `PanelSymbolHeader` to match mockups
- Add `PanelSymbolHeader` based panels to `FunnelPage` example
- Document funnel page specific CSS classes
> Polish Funnel Page Styles

- CHANGELOG.md
- src/Components/DapperScrollbars/DapperScrollbars.tsx
- src/Components/DapperScrollbars/Documentation/DapperScrollbars.stories.tsx
Closes https://github.com/influxdata/influxdb/issues/15633
Adds local state to DapperScrollbars to persist scroll position. This prevents the scrollbar from jumping back to the default position when parent elements are re-rendered.
> fix: add local state to DapperScrollbars to persist scroll position

- package.json
- src/Components/Panel/Composed/PanelSymbolHeader.tsx
Noticed a circular dependency error when building Clockface
- Import `PanelHeader` directly into `PanelSymbolHeader` rather than from the index
- Make `PanelSymbolHeaderProps` extend `PanelHeaderProps`
- Ensure flexbox layout props are passed through to `PanelHeader`
- Create yarn script that runs `prettier:fix` and `eslint:fix` simultaneously
> Fix circular panel dependency

- CHANGELOG.md
- src/Components/ResourceList/Documentation/ResourceList.stories.tsx
- src/Components/ResourceList/List/ResourceListBody.tsx
Closes https://github.com/influxdata/clockface/issues/421
When ResourceList.Body receives boolean false for its children, then it should render the empty state rather than a blank.
> fix: use empty state in ResourceList.Body when children is boolean false

- CHANGELOG.md
- src/Components/Button/Composed/ConfirmationButton.tsx
- src/Components/DatePicker/Composed/DateRangePicker.tsx
- src/Components/Panel/Composed/PanelSymbolHeader.tsx
- src/Components/Panel/Family/PanelBody.tsx
- src/Components/Panel/Family/PanelFooter.tsx
- src/Components/Panel/Family/PanelHeader.tsx
- src/Components/Tabs/TabsContainer.tsx
Closes #425
Replace `data-testid` with `testID` props in components overriding testID.
PanelHeader now displays correct testID.
> fix testID override

- CHANGELOG.md
- package.json
- src/Components/Button/Button.scss
- src/Components/Button/Composed/LinkButton.tsx
- src/Components/Button/Documentation/Button.stories.tsx
- src/Components/Button/Documentation/LinkButton.md
- src/Components/RightClick/Base/RightClickMenuItem.tsx
- src/Styles/typography.scss
- src/Types/index.tsx
Closes #420 
Closes #419 
- Introduce `LinkButton` component
- Create enums for `target` and `rel` props of anchor elements
- Pass back optional event object to `RightClickMenuItem` click handler
> Introduce LinkButton component

- CHANGELOG.md
- rollup.config.js
Closes #
Exports ours variables.scss file as a plain scss file so anything that depends on clockface can access its variables.
this would allow us to do something like the following in Influxdb or giraffe
```scss
@import "reset";
@import "@influxdata/clockface/dist/variables.scss";
@import "mixins";
```
> feat: export variables.scss as a plain scss file for import

- CHANGELOG.md
- src/Components/AppWrapper/Documentation/AppWrapper.stories.tsx
- src/Components/TreeNav/TreeNav.scss
- src/Components/TreeNav/TreeNav.tsx
- src/Components/TreeNav/TreeNavHeader.tsx
- src/Components/TreeNav/TreeNavItem.tsx
- src/Components/TreeNav/TreeNavSubItem.tsx
- src/Components/TreeNav/TreeNavUser.tsx
- src/Components/TreeNav/TreeNavUserItem.tsx
Closes #463 
Closes #461 
Closes #460 
Closes #458 
- Allow `TreeNav` to be opened & closed in mobile mode independently of the `expanded` prop
- Allow optional `shortLabel` prop on `TreeNavItem` to only be displayed when `TreeNav` is collapsed
- Ensure `testID` is assigned when `linkElement` prop is used in any of the `TreeNav` items
- Make sub menus visible so long as `TreeNav` is expanded
- Add `title` attributes to both the username and team elements in `TreeNavUser`
> Improve TreeNav

- CHANGELOG.md
- src/Components/Button/Base/ButtonBaseContrastTester.tsx
- src/Components/Button/Button.scss
- src/Styles/variables.scss
- src/Utils/colors.ts
Closes #459
- Revert gradient mixins to set only the `background` property in shorthand
- Update contrast tester widget
> Fix gradient mixin

- CHANGELOG.md
- src/Components/FunnelPage/Documentation/FunnelPage.stories.tsx
- src/Components/FunnelPage/Family/FunnelPage.scss
- src/Components/Inputs/Composed/VisibilityInput.scss
- src/Components/Inputs/Composed/VisibilityInput.tsx
- src/Components/Inputs/Documentation/Inputs.stories.tsx
- src/Components/Notification/Documentation/Notification.stories.tsx
- src/Components/Notification/Notification.scss
- src/Components/Notification/NotificationDialog.tsx
- src/Components/Overlay/Documentation/Overlay.stories.tsx
- src/Components/Overlay/Overlay.scss
- src/Components/Overlay/OverlayHeader.tsx
Closes #456 
Closes #457 
Closes #462 
Closes #467 
- Ensure `Heading` components that use the classnames from `FunnelPage` maintain proper margins
- Fix appearance of notification dismiss buttons
- Prevent overlay title from overflowing
- Enable optional text wrapping in `OverlayHeader`
- Fix appearance of toggle in visibility input
> Misc Fixes for 2.0.3

- CHANGELOG.md
- src/Components/NavMenu/NavMenuItem.tsx
- src/Components/Tabs/Documentation/Tabs.stories.tsx
- src/Components/Tabs/Tab.tsx
- src/Components/Tabs/Tabs.scss
- src/Components/TreeNav/TreeNavHeader.tsx
- src/Components/TreeNav/TreeNavItem.tsx
- src/Components/TreeNav/TreeNavSubItem.tsx
- src/Components/TreeNav/TreeNavUserItem.tsx
- src/Types/index.tsx
Closes #468 
- Create a shared type for this type of prop called `RenderLinkElement`
- Refactor `Tab` to offer a `linkElement` prop akin to `TreeNav` components
> Allow Tab component to accept links

- CHANGELOG.md
- src/Components/Inputs/Toggle.tsx
Replace `defaultChecked` attribute with checked making it always a controlled component.
> fix(clockface): use correct attribute

- CHANGELOG.md
- src/Components/ResourceList/Card/ResourceCardEditableName.tsx
- src/Components/ResourceList/Card/ResourceCardName.tsx
Closes #478 
- Ensure `testID` and `onClick` are attached to the same DOM element
> Fix ResourceName TestID issue

- CHANGELOG.md
- src/Constants/colors.ts
- src/Types/Types.stories.tsx
- src/Types/index.tsx
- Add `Comet` and `Planet` from old color palette in as `Galaxy` and `Pulsar` for use in brand gradients
- Add 3 single-hue gradients (light, normal, dark) for each color spectrum
> Single Hue Gradients

- CHANGELOG.md
- src/Components/Button/Composed/ConfirmationButton.tsx
- src/Components/Button/Documentation/Button.stories.tsx
Expose `onShow` and `onHide` props in `ConfirmationButton` component.
> feat(clockface): expose onShow & onHide props

- CHANGELOG.md
- src/Components/Form/FormElement.tsx
- src/Components/Form/FormLabel.tsx
- src/Components/Form/FormValidationElement.tsx
Closes #485
- Add `htmlFor` prop to `FormLabel`
- Expose `htmlFor` prop in `FormElement` and `FormValidationElement` and pass through to `FormLabel`
> Add htmlFor prop to FormLabel

- CHANGELOG.md
- src/Components/IndexList/IndexList.scss
Closes https://github.com/influxdata/influxdb/issues/17635
Closes #488 
Remove the background color which is the same value as the text color. This applies to IndexList body when it is empty.
BEFORE: With text and background color the same
AFTER: Correct background color and text color
> fix(clockface): remove same color used by text from the background in IndexList body

- CHANGELOG.md
- src/Components/Form/Documentation/Form.stories.tsx
- src/Components/Form/Documentation/FormElement.md
- src/Components/Form/Form.scss
- src/Components/Form/FormElement.tsx
- src/Components/Form/FormLabel.tsx
- src/Components/Form/FormValidationElement.tsx
Closes #494 
This change should allow inputs to be rendered inside labels (which has better accessibility) without breaking the API
- Render `FormLabel` as a `<div />` instead of `<label />` unless `htmlFor` is passed in
- Add optional `htmlFor` prop to `FormElement` & `FormValidationElement`
- If a value is passed in `FormElement` renders as a `<label />` instead of `<div />`
- Bump label font size from `12px` to `13px`
> Improve FormElement Accessibility 

- CHANGELOG.md
- src/Components/Dropdowns/Documentation/Dropdowns.stories.tsx
- src/Components/Dropdowns/Dropdown.scss
- src/Components/Dropdowns/DropdownItem.tsx
- src/Components/Dropdowns/DropdownLinkItem.tsx
Closes #490 
- Allow both `DropdownItem` and `DropdownLinkItem` to be disabled
- Update documentation for `DropdownMenu` to make it easier to test the above changes
> Add optional "disabled" prop to DropdownItem

- CHANGELOG.md
- src/Components/DapperScrollbars/DapperScrollbars.tsx
- src/Components/DapperScrollbars/Documentation/DapperScrollbars.stories.tsx
- src/Components/DapperScrollbars/Documentation/DapperScrollbarsSynchronized.md
- src/Components/Dropdowns/DropdownMenu.tsx
- src/Components/ResourceList/Card/ResourceCardMeta.tsx
Closes #476 
- Expose `onScroll` and `onUpdate` props in `DapperScrollbars` from `react-scrollbars-custom` library
- Add story with 2 instances of `DapperScrollbars` that have synchronized scrolling
- This example is a way to ensure the required functionality in InfluxDB can be built locally
- Create types for the events returned to `onScroll` and `onUpdate` as well as the handler functions
- This was challenging as the typing within the library is highly unusual and is not exported
> Add scroll additions

- package.json
- Require Yarn `1.22.4` or higher
Running a build with this version of yarn works. It's possible that it could also build fine with a slightly older version as well but that has not been tested
> Require newer version of Yarn to ensure passing builds

- .storybook/Story.scss
- CHANGELOG.md
- src/Components/Popover/Base/Popover.scss
- src/Components/Popover/Base/Popover.tsx
- src/Components/Popover/Base/PopoverDialog.tsx
- src/Components/Popover/Documentation/Popover.md
- src/Components/Popover/Documentation/Popover.stories.tsx
- src/Styles/variables.scss
- src/Utils/index.ts
- src/Utils/popovers.ts
Closes #501 
- Popovers can be dismissed by hitting the escape key
- The dialog component can be focusable and receive keyboard events
- Keyboard events bubble up to the portal containing the popover and then it closes
- `PopoverDialog` will make itself the browser's active element if nothing else is in focus
- Update documentation
- Explain nuances of prop combinations
- Add more permutations of props for manual testing
- Round numbers down to whole numbers when calculating popover position
- This prevents fuzzy sub-pixel rendering of popovers
- If `visible` is true it will supersede the escape key behavior in the interest of complete external control
Example of `PopoverDialog` deferring focus to an input with `autofocus={true}`:
> Allow popovers to be closed via the Escape key

- CHANGELOG.md
- src/Components/Notification/Notification.scss
- src/Components/Notification/Notification.tsx
- src/Components/Overlay/Overlay.scss
- src/Components/Overlay/Overlay.tsx
- src/Components/Popover/Base/Popover.scss
- src/Components/Popover/Base/Popover.tsx
- src/Components/RightClick/Base/RightClick.scss
- src/Components/RightClick/Base/RightClick.tsx
- src/Sandbox/Portals.md
- src/Sandbox/Portals.stories.tsx
- src/Styles/portals.scss
- src/Styles/shared.scss
- src/Styles/variables.scss
- src/Utils/index.ts
- src/Utils/portals.ts
- src/index.ts
- Having a dedicated portal element for every instance of a portal-based component can result in a lot of re-rendering
- Since the previous decision was to enable portal-based components to be used independently of the rest of Clockface, this changeset preserves that goal
- Introduce `usePortal` hook and export alongside components
- Refactor portal-based components to use `usePortal` hook
- `usePortal` creates a portal element as soon as it is needed, then it remains in place for all subsequent components to use.
- Ensures that a single portal element is always visible
- Refactor `z-index` variables
- Notifications will always be on top
- Elements sent to the portal will stack in the order they were sent
- This follows the users journey and feels natural
- Create storybook section called …
> Refactor Portal-Based Components

- CHANGELOG.md
- package.json
Relaxes the Yarn engine version requirement to `>=1.16.0` to prevent breaking CI.
> fix(clockface): relax engine requirement

- CHANGELOG.md
- src/Components/Popover/Base/Popover.tsx
- src/Components/Popover/Base/PopoverDialog.tsx
- src/Components/Popover/Documentation/Popover.md
- src/Utils/portals.tsx
Closes #537
- Rework how event listeners get added to portals
- Allow elements passed in to `usePortal` to be forced to the top
- Only needed this for 1 instance in InfluxDB
- Not very elegant but allows e2e test to pass
- Make popovers less likely to lose focus
- Guard against trigger not yet existing before applying intersection observer
> Fix usePortal Hook

- CHANGELOG.md
- src/Components/TreeNav/TreeNav.tsx
- src/Components/TreeNav/TreeNavSubItem.tsx
Closes #539 
Closes #538 
- Add `testID`s to the toggle and mobile toggle elements of `TreeNav`
- Ensure the `testID` on `TreeNavSubItem` is not duplicated when a link element is passed in
> Improve TreeNav testIDs

- .eslintrc.json
eslint: makes curly braces required
```js
// not so good, very easy to introduce bugs, relies on machines to save us
if (condition)
exit(0)
// more thoughtful approach
if (condition) {
exit(0)
}
> chore: make curly braces required

- CHANGELOG.md
- src/Components/Overlay/Documentation/Overlay.stories.tsx
- src/Components/Overlay/Overlay.tsx
- src/Sandbox/Portals.stories.tsx
Co-Authored-By: Shmuel Lotman <29473622+ShmuelLotman@users.noreply.github.com>
- Only add escape key listeners so long as an overlay is visible
- Remove escape key listeners when overlay is not visible
> refactor: improve escape key behavior for overlays

- rollup.config.js
Closes #562
Changes the `src` argument to the Rollup `copy` plugin to be more specific. The glob `*/**/Images/*` is too generic and can match the `dest` argument `dist/Images` causing error "Source and destination must not be the same". 
The only image I found in the repo was under `src` directory so I changed the the glob to `src/**/Images/*`. 
> fix: Makes rollup copy src specific to avoid src/dest conflict issue

- src/Components/Inputs/Composed/RangeSlider.scss
- src/Components/Inputs/Composed/RangeSlider.tsx
- src/Components/Inputs/Documentation/Inputs.stories.tsx
- src/Types/index.tsx
Closes #
Adds ability to have vertical range slider by passing in Vertical as part of new ComponentDirection enum
> feat: create ability to set vertical range slider

- src/Components/Button/Documentation/ButtonBase.md
- src/Components/Inputs/Toggle.tsx
also adding pretty-quick
- you can just call 'yarn pretty-quick' at the command line, and only the files you changed will get prettier run on them;
it is so much quicker and easier to use  (takes 5-10 seconds instead of 2-3 minutes)
Closes #566 
the on-click listener is now on the entire div; so that clicking on the children will toggle as well
(b/c of the explicit onclick handler, the 'for' linking the labels to the input does not toggle the button at all)
> fix:  labels on toggle buttons are now clickable

- src/Components/Inputs/Composed/RangeSlider.scss
- src/Components/Inputs/Composed/RangeSlider.tsx
- src/Components/Inputs/Documentation/Inputs.stories.tsx
Closes #
Enables an option that allows the user to have a displayed value counter next to the range slider max value, as a fraction
> Range Slider With Value Exposed Option

- src/Components/Dropdowns/Dropdown.tsx
supporting/required for 20195 in the ui repository
Adding 2 optional properties, if those properties are not there then the. dropdown works exactly as it did before these changes
from the documentation:
onClickAway :  Optional method that is triggered when the user clicks outside of/away from the dropdown 
menuOpen:  string
optional way for the owner of this dropdown to set the menu state:
'open':  the menu will be open
'closed': the menu will be closed
any other string will be ignored.
and the menu state (open/closed) only changes when the string changes.
so the owner is responsible for resetting the string
(if the string is set to 'open', and then the user closes it, and the code sets it to open again,
unless the owner/code sets it to something else in between (like 'ignore' or …
> Feat: dropdown enhancements

- src/Components/EmptyState/EmptyStateText.tsx
- src/Styles/variables.scss
- src/Utils/portals.tsx
Related: https://github.com/influxdata/ui/issues/520
Made some small tweaks to improve the accessibility and best practice scores from lightouse. 
1) Changed EmptyState's header from an h4 to an h2 so that our headers decrease sequentially. 
1) Changed EmptyState's font color to improve contrast ratio
1) Removed the tabIndex=1 from portals.
Also see this UI PR: https://github.com/influxdata/ui/pull/764
> chore: improve lighthouse accessibility score

- src/Components/Form/FormElement.tsx
Closes #
This PR passes along the testID to the FormElementError so that a unique testID can be gotten for the form error. This was already in place, but no testID was being passed down 
> fix: propagate testID to error label

- src/Components/Form/FormElement.tsx
- src/Components/Form/FormElementError.tsx
Updated the FormElement to allow for an additional testID to be passed to the FormElement that will be propagated onto the FormErrorMessage. This will allow for more customized testing on error messages. 
> chore: updated FormElement props and FormElementError to allow for custom testIDs to be passed in for the formelementerror

- CHANGELOG.md
- src/Components/ResourceList/Card/ResourceCardName.scss
Closes #
For disabled cards, there used to be a color specific opacity defined in css that was overriding the disabled-error combo. For disabled states, changing to generic opacity vs color specific opacity
> Fix: color specific opacity to generic opacity

- src/Components/Overlay/Documentation/Overlay.stories.tsx
- src/Components/Overlay/Overlay.scss
- src/Components/Overlay/OverlayContainer.tsx
Closes #201
Added a new prop to overlay 'fullScreen', if true, it will make the overlay span the entire width and height of the screen.
> feat: optional full screen overlay w/ a fullscreen prop

- PUBLISHING.md
- publish
Closes #612 
Updates the publish script to require a version
```sh
./publish 2.7.5
```
> chore: update publish script

- CHANGELOG.md
- src/Components/Button/Base/ButtonBase.tsx
- src/Components/Button/Composed/Button.tsx
- src/Components/Button/Composed/CTAButton.tsx
- src/Components/Button/Composed/ConfirmationButton.tsx
- src/Components/Button/Composed/DismissButton.tsx
- src/Components/Button/Composed/LinkButton.tsx
- src/Components/Button/Composed/SquareButton.tsx
- src/Components/Button/Documentation/Button.stories.tsx
- src/Components/Dropdowns/Documentation/Dropdowns.stories.tsx
- src/Components/Dropdowns/DropdownButton.tsx
Closes #122 
You can pass in an optional disabledTitleText as a prop to button and button-adjacent components. 
When a button component is in the status of 'disabled', it will show disabledTitleText instead of regular title text.
If there is no disabledTitleText defined, it will show regular title text
> Button disabled text

- CHANGELOG.md
- src/Components/Inputs/Input.scss
- src/Components/Inputs/Input.tsx
- src/Components/Inputs/StatusIndicator.scss
Closes #631 
With Inputs, when status is not default, we add padding to the right equal to the size of the status indicator (the error symbol, valid symbol .. etc). This way no part of the last few characters will be hidden. I also reduced the range of the shadow effect of the status indicator so that the shadow doesn't cover the characters either.
> add spacing to input field so that last few chars don't get hidden

- src/Components/IndexList/IndexListHeaderCell.tsx
Closes https://github.com/influxdata/ui/issues/2086
ClassName for IndexList header for the arrow indicating sort direction was incorrect. Was originally `icon caret-down`, but is supposed to `cf-icon caret-down`. See `IndexList.scss` line 181.
> fix: changed to correct classname

- package.json
- src/Styles/variables.scss
changed z-index of overlays from 9200 to 12000; so it will be on top of everything 
(including tooltips from giraffe, which are at 9999)
also bumping the version number.
very minor, small surgical change
> chore: raising z-index of overlays so they are on top of everything

- .eslintrc.json
- package.json
- src/Components/Popover/Documentation/Popover.stories.tsx
- yarn.lock
Closes #665 
- Activates the eslint rule for React hooks
- Fixes a minor error in one of the storybook examples
> chore: add eslint rule for React hooks

- src/Components/PaginationNav/paginationTruncationItem.tsx
Closes https://github.com/influxdata/ui/issues/2036
I added the `status = ComponentStatus.disabled` so that the ellipses can not be clicked. 
> fix: make paginationTruncationItem.tsx component status disabled

- src/Components/TreeNav/TreeNavSubMenu.tsx
Closes #688 
When collapsed, the nav item used to trigger on click; now it triggers on hover for better discoverability
https://user-images.githubusercontent.com/12561526/139694688-f98bd831-8b35-45c3-8c5a-4459389e6ea0.mp4
> fix: change to onhover rather than on click

- package.json
- src/Components/PaginationNav/PaginationItem.tsx
Closes https://github.com/influxdata/idpe/issues/12181
The button that makes up the PaginationItem needs to accommodate the content and be of the right width. 
> fix: PaginationItem button width should respect the content so it fits

- package.json
- src/Components/Page/PageContents.tsx
Part of https://github.com/influxdata/ui/issues/3078
Just exposes the props of the `DapperScrollBar` to the `Page` component.
> feat: scrollbar size prop for Page component

- CHANGELOG.md
- src/Components/ProgressBar/ProgressBar.scss
- src/Components/ProgressBar/ProgressBar.tsx
Closes #
Added `displayRemaining` boolean flag which allows you to view remaining value instead of used value.
Also add prefix and suffix to value/max labels.
If `displayRemaining` boolean value is passed as `true` then following is the affect on the ProgressBar. Also added prefix and suffix to value/max labels.
BEFORE
AFTER
> feat: add display remaining feat for ProgressBar

- package.json
a fix was released last night that didn't bump the version in package.json. This makes sure they stay in sync.
> chore: make package.json version number match release number

- CHANGELOG.md
- package.json
- yarn.lock
Adds a [yarn resolution](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) for immer.
> chore: added resolution to force version 9.0.6 and greater of immer

- CHANGELOG.md
On the previous PR, I didn't update the changelog's version number. Oops, this fixes that.
> chore: fix erroneous changelog version

- package.json
- src/Components/DapperScrollbars/DapperScrollbars.tsx
When you unchecked an item in the list, the entire list would jump to the top. After this change, when you uncheck an item, the list will not show any change other than the actual unchecking action.
> fix: fix list uncheck flickering

- package.json
- src/Components/List/List.tsx
As the height of a list item was hard-coded to `24px`, the calculation of `scrollTo` position became out of sync for `xs` because of the extra headers in the list as well as the mismatch of the height of the actual item. I think a good solution would be to use refs for list items but we'd have to take performance into consideration.
For other sizes, the height was still `24` which was absolutely inaccurate and I measured all the sizes and made a map for each of the respective sizes and now the out of sync issue is still there but is very minimal.
> fix: fix scrollto positioning issue

- package.json
- src/Components/ResourceList/Card/ResourceCardEditableName.scss
- src/Components/ResourceList/Card/ResourceCardEditableName.tsx
- src/Components/ResourceList/Card/ResourceCardName.scss
Part of https://github.com/influxdata/clockface/issues/702
Changes the CSS so that the icon is always aligned with the **first line** of the name.
> fix: resource card editable name pencil css fix

- package.json
- src/Utils/Tests/hexCodeValidation.test.ts
- src/Utils/hexCodeValidation.ts
Part of https://github.com/influxdata/ui/issues/3716
The input validation for the color input now invalidates a string that has more than one `#` and if character G / g is typed. 
> fix: color picker input invalidate more than one '#'

- CHANGELOG.md
- package.json
- yarn.lock
Fixes storybook by undoing this PR https://github.com/influxdata/clockface/pull/719
> revert: revert commit 493f0b, which upgraded marked from 0.7.0 => 4.0.10 and broke storybook

- CHANGELOG.md
- package.json
- src/Components/ColorPicker/ColorPicker.scss
- src/Components/ColorPicker/ColorPicker.tsx
- src/Components/ColorPicker/ColorPreview.scss
- src/Components/ColorPicker/ColorPreview.tsx
- src/Components/Dropdowns/Composed/CreatableTypeAheadDropdown.tsx
- src/Components/Dropdowns/Documentation/CreatableTypeAheadDropdown.md
- src/Components/Dropdowns/Documentation/Dropdowns.stories.tsx
- src/Components/Inputs/Input.tsx
Closes influxdata/ui#3680
This PR created a new component called "Creatable Type Ahead Dropdown," a more flexible version of "Type Ahead Dropdown." 
Here are the features provided with this new component:
- Type ahead search in dropdown menu
- Accept typed values that are not in the dropdown menu
- Customizable dropdown items
- Optional color preview
- Add a new component `CreatableTypeAheadDropdown`
- Add this new component into storybook with examples
- Add `colorPreview` prop to `Input` component
- Move `ColorPreview` component and its style into a single file
https://user-images.githubusercontent.com/14298407/152875227-c79a1825-d8e4-4286-9764-c68b63da5899.mov
> feat: add new component Creatable Type Ahead Dropdown

- CHANGELOG.md
- package.json
- src/Components/Dropdowns/Documentation/Dropdowns.stories.tsx
- src/Components/Dropdowns/DropdownButton.scss
- src/Components/Dropdowns/DropdownButton.tsx
Supports https://github.com/influxdata/ui/issues/3404  - a new set of dropdowns will be put into Band View's options to allow the user to select only valid column names. The 3 different columns that have selectable names must choose different names. Indicate to the user that a dropdown has an invalid selection.
This is a minimalist feature. It simply allows the `Dropdown.Button` to add a box-shadow when the component status is error. Completely opt-in and backwards compatible.
- adds component status to Dropdown buttons
- adds box shadow to indicate error status for Dropdown buttons
**_UPDATED_** to use a solid border without shadow:
> feat: add error status to dropdown button

- CHANGELOG.md
- package.json
- src/Components/Dropdowns/DropdownButton.scss
Part of https://github.com/influxdata/ui/issues/3404
Previously, dropdown buttons were updated to allow for error status, which adds a visual border around the button. However, the box shadow was not removed when the button is focused. We want to remove all box shadows for dropdown buttons that are in error status.
Removes the conflicting box shadow around dropdown buttons when in error status.
BEFORE:
AFTER:
> fix: remove box shadow from dropdown buttons when in error status

- package.json
- src/Components/ResourceList/Card/ResourceCardEditableName.tsx
- src/Components/ResourceList/Card/ResourceCardName.scss
Part of: https://github.com/influxdata/clockface/issues/723
Changes the `span` to an `a` tag to make the CMD-Click behavior consistent across environments.
https://user-images.githubusercontent.com/18511823/155027682-361874f6-d93c-4774-ae20-3cdfcfa74214.mov
> fix: ResourceCardName make <a> tag instead of <span>

- .gitignore
**npm** requires new steps to publish when requiring 2FA (two-factor authentication). One of the steps involves inserting a token into your local **.npmrc** file, which should remain local so that we do not leak tokens.
- add **.npmrc** to **.gitignore**
> chore: add .npmrc to gitignore to support publishing without leaking tokens

- CHANGELOG.md
- package.json
- src/Components/Form/FormValidationElement.tsx
Closes https://github.com/influxdata/clockface/issues/743
FormValidationElement now compares new values to the original value before enabling validation. See the attached issue for more context.
https://user-images.githubusercontent.com/6411855/157991870-64d42687-7d13-46ba-a69e-ff01b12e8009.mov
> fix: FormValidationElement compares values

- CHANGELOG.md
- package.json
- src/Components/FunnelPage/Documentation/FunnelPage.stories.tsx
- src/Components/FunnelPage/Family/FunnelPage.tsx
- src/Types/index.tsx
Closes #
Added the three new brand colors and updated the funnel page to use these colors by default.
PurpleX,
CetaceanBlue,
DogwoodRose
> feat: Added new Brand Colors + Updated Funnel Page default Colors

- CHANGELOG.md
- package.json
- src/Components/ResourceList/Card/ResourceCardEditableName.scss
- src/Components/ResourceList/Card/ResourceCardEditableName.tsx
Connects #723
Adds an `href` property to `ResourceCardEditableName`. The `href` property is what the browser uses to infer that the element is a link and should have the proper context menu that includes `Open Link in New Tab` and `Open Link in New Window`.
The property will need to be passed into `ResourceCard.EditableName` on the ui side for this to work completely.
**Dashboards**
**Tasks**
> feat(ResourceCard): add href property for proper browser context menu

- src/Components/Logo/InfluxLogo.scss
- src/Components/Logo/InfluxLogo.tsx
- src/Components/Logo/Logos/AuxiliaryText/Cloud.tsx
- src/Components/Logo/Logos/AuxiliaryText/Enterprise.tsx
- src/Components/Logo/Logos/AuxiliaryText/OpenSource.tsx
- src/Components/Logo/Logos/BaseText/InfluxData.tsx
- src/Components/Logo/Logos/BaseText/InfluxDb.tsx
- src/Components/Logo/Logos/BaseText/Telegraf.tsx
- src/Components/Logo/Logos/Logomarks/Kubo.tsx
- src/Components/Logo/Logos/Logomarks/KuboOld.tsx
- src/Components/Logo/Logos/Symbols/Registered.tsx
- src/Components/Logo/Logos/Symbols/Trademark.tsx
Closes #
Evened out the Vertical alignment and updated the sizing of the logos to match what was formerly in prod.
> fix: Updated Vertical Alignment and Logo sizing

- CHANGELOG.md
- package.json
- src/Components/TreeNav/TreeNavSubMenu.tsx
Closes #
PR adds an optional prop to `TreeNavSubMenu` component with a default value set to `PopoverPosition.ToTheRightTop`. This will give `TreeNavSubMenu` the ability to change the position of the popover modal. 
https://user-images.githubusercontent.com/66275100/169159301-d2993d23-e531-47e3-8554-b0cba6a70339.mov
> add an optional prop to TreeNavSubMenu

- package.json
- yarn.lock
https://github.com/influxdata/clockface/pull/777 had updates for ansi-regex, but I missed the one for 4.1.0 -> 4.1.1 (sorry for the extra PR). `yarn test` passes.
> chore: use resolution to resolve ansi-regex 4.1.x

- CHANGELOG.md
- package.json
- src/Components/Dropdowns/Composed/MenuDropdown.tsx
- src/Components/Dropdowns/Composed/MenuDropdownStyles.scss
- src/Components/Dropdowns/Dropdown.scss
- src/Components/Dropdowns/DropdownHrefItem.tsx
- src/Components/Dropdowns/DropdownItem.tsx
- src/Types/index.tsx
Closes https://github.com/influxdata/clockface/issues/787
1. Added an `onSelectOption` handler which sends the information back to the UI when an option is selected.
2. Adds the checkmark instead of the blue background for the selected option.
3. When dropdown typeahead was cleared it cleared the state of the whole component, this is undesirable. 
4. Some styling changes to make it match the figma design.
https://user-images.githubusercontent.com/18511823/175786985-be13c653-cdf3-4fb3-af10-afe046cefa7b.mov
> fix: MenuDropdown fixes

- CHANGELOG.md
- package.json
- src/Components/Dropdowns/Composed/MenuDropdown.tsx
- src/Components/Dropdowns/Composed/MenuDropdownStyles.scss
Closes #
Simple styling change so it shows the Checkmark when the dropdown is selected.
> fix: Styling menudropdown

- CHANGELOG.md
- src/Components/SubwayNav/SubwayNav.tsx
- src/Components/SubwayNav/SubwayNavStep.tsx
We currently don't have the ability to have checkbox based on a custom criteria. Instead of adding a criteria function, I am adding an optional `isCompleted` boolean per step. If the boolean exists for a step then that boolean will take precedence. If it doesn't exist in the navigation step, then the regular logic will be applied.
NOTE: Please note that the last step is now checked in the AFTER gif. Earlier, this wasn't possible. Reason this is checked is because I set `isComplete` for that step to true.
> feat: add custom check ability per step

- CHANGELOG.md
- package.json
- src/Components/Dropdowns/Composed/MenuDropdown.tsx
Per [UI 4047](https://github.com/influxdata/ui/issues/4047) and [UI 4051](https://github.com/influxdata/ui/issues/4051), the multi-org dropdown:
1. Should not display the 'switch account' or 'switch org' menu if there's only one account or org.
2. Should check for the currently 'selected' account or org's `id` after converting to a string: Org arrays have `string` ids, but account arrays have `number` ids.
*EDIT*: Removed prior change involving sorting selected item to first part of the array. That is easier to handle in a sort in the UI.
> fix: Multi-org dropdown shouldn't show typeahead if only one account/org

- CHANGELOG.md
- package.json
- src/Components/Button/Button.scss
- src/Components/Dropdowns/DropdownButton.scss
- src/Components/Dropdowns/DropdownButton.tsx
Closes https://github.com/influxdata/clockface/issues/800
Updated the dropdown component to enable a spinner for the Loading state.
Button loading state has changed to no longer have a transparency.
> feat: Enables Loading Spinner for Dropdowns

- CHANGELOG.md
- package.json
- src/Components/Dropdowns/Composed/TypeAheadDropDown.tsx
Closes https://github.com/influxdata/clockface/issues/824
This is a known issue with Safari. 
https://stackoverflow.com/questions/54229359/why-does-select-not-work-on-safari-with-reactjs
After change: 
https://user-images.githubusercontent.com/18511823/185027574-df232908-4b4c-4466-bdb6-5626249ae3a1.mov
> fix(TypeAheadDropdown): input select on focus now works in Safari

- CHANGELOG.md
- package.json
- src/Components/SelectableCard/SelectableCard.scss
Closes https://github.com/influxdata/clockface/issues/711
The titles explains it mostly. The css filters were causing performance issues on the selectable cards. They have been removed now.
> fix: Removed CSS Filters from Selectable Cards

- CHANGELOG.md
- package.json
- src/Components/Inputs/Input.scss
Closes https://github.com/influxdata/clockface/issues/810
Removed the text color and opacity when an input is disabled.
Before this change, the text was hard to read from an accessibility standpoint
Old:
New:
> fix: Removed Text Color and Opacity from Disabled Input (Accessibility)

- CHANGELOG.md
- package.json
- src/Components/DraggableResizer/Documentation/DraggableResizer.stories.tsx
- src/Components/DraggableResizer/DraggableResizer.tsx
Closes https://github.com/influxdata/clockface/issues/834
Fixed a bug that prevented the last odd panel from collapsing in the 1 (right or down) direction.
Created a proper offset value for odd and even numbered panels. 
Also updated storybook to have 1 example of even and odd panels.
> fix: Odd Panels would not Collapse properly

- src/Components/Accordion/Accordion.scss
- src/Components/Accordion/Accordion.tsx
- src/Components/Accordion/AccordionHeader.tsx
- src/Components/Accordion/Documentation/Accordion.stories.tsx
- src/Styles/variables.scss
Closes: https://github.com/influxdata/clockface/issues/822
Accordion updates for Clockface 4 to match figma. 
https://user-images.githubusercontent.com/18511823/194227563-fe593f10-590e-4615-89ba-c546c5a0f917.mov
> feat(Accordion): Clockface 4 Updates

- src/Components/Button/Button.scss
- src/Components/Dropdowns/Dropdown.scss
- src/Components/Dropdowns/DropdownMenu.tsx
- src/Components/Inputs/Input.scss
- src/Styles/variables.scss
Closes https://github.com/influxdata/clockface/issues/838
Couple screenshots:
`SelectDropdown`:
`TypeAheadDropdown`:
`CreateableTypeAheadDropdown`: 
`MultiSelect`:
> feat(Dropdowns): Clockface 4 dropdown updates

- src/Components/Dropdowns/Dropdown.scss
- src/Components/Inputs/Composed/RangeSlider.scss
- src/Components/Inputs/Input.scss
- src/Components/Inputs/StatusIndicator.scss
- src/Components/Inputs/Toggle.scss
- src/Components/SlideToggle/SlideToggle.scss
- src/Styles/variables.scss
- src/Types/index.tsx
- src/Utils/index.ts
**Please note, the changes are going into a running master for Clockface 4**
Closes https://github.com/influxdata/clockface/issues/839
Closes https://github.com/influxdata/clockface/issues/865
Inputs:
Toggle:
RangeSlider:
Slide toggles:
Radio Toggles
> feat(inputs): clockface 4 updates

- CHANGELOG.md
- package.json
- src/Components/Dropdowns/Composed/MultiSelectDropdown.tsx
- src/Components/Dropdowns/Documentation/Dropdowns.stories.tsx
Closes: https://github.com/influxdata/clockface/issues/884
Closes: https://github.com/influxdata/ui/issues/6117
* Adds prop `isSearchable` and `searchbarInputPlaceholder`
* Default behaviour is the `isSearchable = false`
Video:
https://user-images.githubusercontent.com/18511823/199553836-0f3cbd3f-3aee-46f8-8a26-401461bb076a.mov
> feat(MultiSelect): make MultiSelectDropdown optionally searchable

- src/Components/Accordion/Accordion.scss
- src/Components/Button/Button.scss
- src/Components/Dropdowns/Dropdown.scss
- src/Components/Inputs/Composed/RangeSlider.scss
- src/Components/Inputs/Toggle.scss
- src/Components/SlideToggle/SlideToggle.scss
- src/Styles/variables.scss
- src/Types/index.tsx
- src/Utils/index.ts
Closes [#849](https://github.com/influxdata/clockface/issues/849)
> feat(Clockface 4): labels

- src/Components/FunnelPage/Documentation/FunnelPage.stories.tsx
- src/Components/Notification/Documentation/Notification.stories.tsx
- src/Components/Notification/Notification.scss
- src/Components/Notification/Notification.tsx
- src/Components/Notification/NotificationDialog.tsx
- src/Sandbox/Portals.stories.tsx
- src/Types/index.tsx
Closes https://github.com/influxdata/clockface/issues/832
> feat(Clockface 4): Notifications

- package.json
- yarn.lock
* chore: use resolution for various @storybook's loader-utils to 2.0.3
* chore: resolve devDeps and remaining @storybook to loader-utils 1.4.1
These resolutions should be able to be removed once `clockface` moves to webpack5, which allows other devDependencies to be upgraded. For now, resolve `loader-utils` to 2.0.3 and 1.4.1 to address dependabot.
> chore: add resolutions for loader-utils

- src/Components/ProgressBar/ProgressBar.scss
- src/Components/ProgressBar/ProgressBar.tsx
- src/Constants/colors.ts
- src/Types/index.tsx
Closes https://github.com/influxdata/clockface/issues/855
> feat(Clockface 4): Progressbar

- package.json
- yarn.lock
This reverts commit 4e486c157f2cda9d7ae87606ef2467dc7dbd9a17.
@mavarius reported to me that `yarn storybook` errored out after recent PRs. I was able to determine that 4e486c157f2cda9d7ae87606ef2467dc7dbd9a17 was the culprit, so revert it for now.
> Revert "chore: add missed resolution for loader-utils 1.4.2 (#904)"
