CHANGELOG.md, package.json
=> Bump version 0.0.20

src/Components/ColorPicker/ColorPickerSwatch.tsx, src/Components/DraggableResizer/DraggableResizerPanel.tsx, src/Components/Dropdowns/Family/Dropdown.tsx, src/Components/Dropdowns/Family/DropdownMenu.tsx, src/Components/FlexBox/FlexBoxChild.tsx, src/Components/Form/FormDivider.tsx, src/Components/IndexList/IndexListHeaderCell.tsx, src/Components/Inputs/Input.tsx, src/Components/Inputs/TextArea.tsx, src/Components/Label/Label.tsx, src/Components/Overlay/OverlayContainer.tsx, src/Components/Overlay/OverlayMask.tsx, src/Components/Page/PageHeaderCenter.tsx, src/Components/Page/PageHeaderLeft.tsx, src/Components/Page/PageHeaderRight.tsx, src/Components/Panel/Panel.tsx, src/Components/Spinners/TechnoSpinner.tsx, src/Components/Table/Table.tsx, src/Components/Table/TableCell.tsx, src/Components/Table/TableHeaderCell.tsx, src/Components/TextBlock/TextBlock.tsx
Addresses feedback from the review of  https://github.com/influxdata/clockface/pull/219
=> refactor: ensure style prop can override other inline styles

CHANGELOG.md, src/Components/SelectableCard/SelectableCard.md, src/Components/SelectableCard/SelectableCard.scss, src/Components/SelectableCard/SelectableCard.stories.tsx, src/Components/SelectableCard/SelectableCard.tsx
Closes #262
Update `SelectableCard` component with top-label design.
=> Update SelectableCard component

CONTRIBUTING.md, README.md
the contributing guide has some basics and will likely need more work, but having an incomplete guide is better than no guide
I mainly focused on documenting our code patterns
=> First pass at a contributing guide

src/Components/Popover/Composed/QuestionMarkTooltip.tsx, src/Components/Popover/Documentation/QuestionMarkTooltip.md
- Ensure props with defaults are optional
- Correct a typo in documentation
=> Tweak QuestionMarkTooltip

CHANGELOG.md, src/Components/Button/Composed/Button.tsx, src/Components/ColorPicker/ColorPicker.scss, src/Components/ColorPicker/ColorPicker.tsx
- Fix squished square buttons
- Fix style bug with color picker
=> Misc Tweaks

src/Components/Button/Composed/ConfirmationButton.tsx, src/Components/ColorPicker/ColorPicker.scss, src/Components/IndexList/Documentation/IndexList.stories.tsx, src/Components/IndexList/IndexList.scss, src/Components/IndexList/IndexListRow.tsx, src/Components/Popover/Composed/QuestionMarkTooltip.tsx, src/Components/Popover/Composed/ReflessPopover.tsx, src/Components/ResourceList/Card/ResourceCard.tsx
Fixing a myriad of bugs discovered while testing this version of Clockface in InfluxDB
- Replace instances of `createRef` with `useRef`
- Fix a bug that prevented context menus from rendering in `ResourceCard`
- Create a prop for brightening `IndexListRow` instead of relying on a parent having a specific class
=> Moar misc tweaks

src/Components/Button/Base/ButtonBaseContrastTester.scss, src/Components/Button/Base/ButtonBaseContrastTester.tsx, src/Components/Button/Documentation/Button.stories.tsx, src/Components/Button/Documentation/ButtonBaseContrastTester.md
=> Add testing widget for ensuring proper contrast in buttons

package.json, src/Components/Inputs/Documentation/Inputs.stories.tsx, src/Components/ResourceList/Documentation/ResourceCard.stories.tsx, src/Components/ResourceList/Documentation/ResourceList.stories.tsx
Closes https://github.com/influxdata/clockface/issues/416
Added prettier scripts and ran them on all files in **/src**
=> feat: add prettier scripts and run on all files

CHANGELOG.md, src/Components/Notification/Documentation/Notification.md, src/Components/Notification/Documentation/Notification.stories.tsx, src/Components/Notification/Notification.scss, src/Components/Notification/Notification.tsx, src/Components/Notification/NotificationDialog.tsx, src/Components/Panel/Family/Panel.tsx, src/Utils/index.ts
Closes #411
Adds `Notification` component family
=> Add Notificaton component

CHANGELOG.md, src/Components/Button/Composed/LinkButton.scss, src/Components/Button/Composed/LinkButton.tsx, src/Styles/typography.scss
Fix bug where exclusion rule in CSS changed the color of navigation items.
=> Remove link color exclusion rule & add LinkButton styles

CHANGELOG.md
Update changelog to 1.1.5 (unreleased)
=> update changelog 1.1.5 (unreleased)

CHANGELOG.md, src/Components/Typography/Documentation/Heading.md, src/Components/Typography/Documentation/Typography.stories.tsx, src/Components/Typography/Heading.tsx
Closes #448
Updated Docs. Also added an onClick handler for the Heading component
=> feat(heading): added onClick event to Heading component

CHANGELOG.md, src/Components/Button/Button.scss, src/Components/Dropdowns/Composed/MultiSelectDropdown.tsx, src/Components/Dropdowns/Composed/SelectDropdown.tsx, src/Components/Dropdowns/DropdownItem.tsx, src/Components/Inputs/Documentation/Inputs.stories.tsx, src/Components/Inputs/Toggle.tsx, src/Styles/variables.scss
Closes #446 
Closes #447 
Closes #450 
- Give `Toggle` a default value for `checked` prop (bugfix)
- Make `Warning` and `Danger` buttons single hue as well as more distinct from other button colors
- Add optional `title` prop to `DropdownItem`
=> Misc Improvements for 2.0.2

CHANGELOG.md, src/Components/Notification/Documentation/Notification.md, src/Components/Notification/NotificationDialog.tsx
Closes #491 
- Add `testID` to notification dismiss button as well as child wrapper element
- Add a "testing" section to the components documentation
=> Add testID to notification dismiss button

CHANGELOG.md, src/Components/Button/Composed/CTAButton.tsx, src/Components/Button/Composed/CTALinkButton.tsx, src/Components/Button/Composed/LinkButton.tsx, src/Components/Button/Documentation/Button.stories.tsx, src/Components/Button/Documentation/CTALinkButton.md
- Add `CTALinkButton` component
- Export `LinkButton` & `CTAButton` props
=> feat(clockface): add CTALinkButton component

CHANGELOG.md
Update changelog with consistent language and add missing item.
=> chore(clockface): update changelog

CHANGELOG.md, src/Components/DatePicker/Documentation/DatePicker.md, src/Components/DatePicker/Documentation/DatePicker.stories.tsx, src/Components/DatePicker/Documentation/DateRangePicker.md, src/Components/DraggableResizer/DraggableResizerHandle.tsx, src/Components/Dropdowns/Documentation/Dropdowns.stories.tsx, src/Components/Form/Documentation/Form.stories.tsx, src/Components/Inputs/Documentation/Inputs.stories.tsx, src/Components/Page/Documentation/page.stories.tsx, src/Components/Panel/Documentation/PanelExampleA.md, src/Components/ResourceList/Documentation/ResourceCard.stories.tsx, src/Components/ResourceList/Documentation/ResourceList.stories.tsx, src/Components/RightClick/Documentation/RightClick.md, src/Types/Types.stories.tsx, yarn.lock
- Run `yarn update` to fix the build errors.
- Address new linter rules
=> Fix dependency issues and address new lint rules

CHANGELOG.md
=> fix(clockface): fix changelog versioning

CHANGELOG.md, src/Components/DapperScrollbars/DapperScrollbars.tsx, src/Styles/variables.scss
Closes #507 
- Use `renderer` offered by `react-scrollbars-custom` to pass in a DOM element instead of just props
- Attach `data-testid` to aforementioned DOM element
=> Add testIDs to DapperScrollbar thumbs

src/Styles/variables.scss
=> fix(clockface): remove comment

CHANGELOG.md, package.json, src/Components/DapperScrollbars/DapperScrollbars.tsx, src/Components/Popover/Composed/QuestionMarkTooltip.tsx
Adds extra dash to test id to match the standard naming convention.
Also fixes changelog version numbering.
=> Fix test ids

CHANGELOG.md, src/Components/List/ListItem.tsx
=> Return Event Object to ListItem onClick Handler

CHANGELOG.md
updating changelog.  that is it.
(for current, unreleased version, also updated an earlier link at @mavarius request)
=> chore: updating changelog.  no code changes at all.

CHANGELOG.md, src/Components/Dropdowns/Dropdown.tsx, src/Components/Dropdowns/index.tsx
updating changelog versions and put todays date on version 2.6.0
=> chore: updating changelog versions and put todays date on version 2.6.0

CHANGELOG.md
=> docs: update change log for 2.6.3

PUBLISHING.md
updating documentation; no code changes
=> chore: updating publishing document to be current and clearer

CHANGELOG.md
Bumping changelog to 2.6.5 for a publication.
=> Changelog to 2.6.5

CHANGELOG.md
Closes #
Changelog updated for publishing
=> change change log for release

publish
uncomments the most important parts of the publish script - the actual publishing.
=> fix: actually publish the changes to npm

publish
=> change publish script

src/Components/PaginationNav/Documentation/PaginationNav.stories.tsx, src/Components/PaginationNav/PaginationNav.tsx
=> Allow the pagination nav to listen to currentPage changes

CHANGELOG.md
=> changelog Update

CHANGELOG.md
=> chore: change log for new icon

CHANGELOG.md, src/index.ts
=> chore: export accordion

CHANGELOG.md
updating changelog.  no other changes
=> update changelog for new release (2.11.4)

CHANGELOG.md, src/Components/FlexBox/FlexBoxChild.tsx
=> adding onClick on flexbox child so we can pass stop propagation

src/Components/TreeNav/Documentation/TreeNav.stories.tsx, src/Components/TreeNav/TreeNav.scss
Closes #691  and in turn, closes influxdata/ui#3093
https://user-images.githubusercontent.com/12561526/139708127-eddfb839-83fd-4a63-a744-59ad73e40d8a.mp4
https://user-images.githubusercontent.com/12561526/139708249-08d6b216-e3a7-43cd-8eb8-5139eb7e0667.mp4
=> fix: hover states actually visually register now

CHANGELOG.md, src/Components/TreeNav/TreeNav.scss
=> fix: changelog and focus state visual state

src/Components/List/List.scss
Closes #693 
https://user-images.githubusercontent.com/12561526/140083524-d23c61ec-ac77-41a7-bcdf-df6dfe646051.mp4
=> fix: color change to re-enforce hierarchy

CHANGELOG.md
=> chore: update changelog w new additions

CHANGELOG.md, package.json, src/Components/Alert/Alert.scss, src/Components/Button/Composed/DismissButton.scss, src/Components/DapperScrollbars/DapperScrollbars.scss, src/Components/DatePicker/DatePicker.scss, src/Components/Dropdowns/Dropdown.scss, src/Components/FlexBox/FlexBox.scss, src/Components/Form/Form.scss, src/Components/Grid/Grid.scss, src/Components/Inputs/Composed/RangeSlider.scss, src/Components/Inputs/Input.scss, src/Components/Label/Label.scss, src/Components/Page/Page.scss, src/Components/Panel/Composed/PanelSymbolHeader.scss, src/Components/SlideToggle/SlideToggle.scss, src/Components/Tabs/Tabs.scss, src/Components/TreeNav/TreeNav.scss, src/Styles/variables.scss
Closes #706
Ran `sass-migrator division` on our scss files. This is the automated output from that tool.
Tested on ui by linking clockface to ui. I didn't see any obvious issues.
=> chore: fix sass warning by not using / operator for division

CHANGELOG.md, package.json
A new version for an internal test.
=> chore: update version numbers for internal test

package.json
Updates the version number for publishing
=> chore: update version for publishing

CHANGELOG.md, package.json
Closes #
Updated the package and change log for https://github.com/influxdata/clockface/pull/762
=> Updated Changelog and Package for 762

CHANGELOG.md, package.json, src/Components/Dropdowns/Composed/MenuDropdown.tsx, src/Components/Dropdowns/Documentation/Dropdowns.stories.tsx, yarn.lock
Connects https://github.com/influxdata/clockface/issues/790
Uses `react-window` to deal with large lists! 
https://user-images.githubusercontent.com/18511823/176742919-1c960ef1-22e3-4d18-b536-5732e29ffd9c.mov
=> feat: react-window for long lists

package.json
Just a version bump in package.json.
=> chore: version bump in package.json to v4.7.2

CHANGELOG.md, package.json, src/Components/Dropdowns/Composed/MenuDropdown.tsx, src/Components/Dropdowns/Composed/MenuDropdownStyles.scss
There were a few unnecessary variables that needed to be removed and some renamed from generic names to more specific ones so it's easier to follow in the future. :)
=> refactor: MenuDropdown Cleanup

CHANGELOG.md, package.json, src/Components/Dropdowns/Composed/TypeAheadDropDown.tsx, src/Components/Dropdowns/Composed/TypeAheadDropDownStyles.scss
Connects: https://github.com/influxdata/ui/issues/4966
https://user-images.githubusercontent.com/18511823/183536198-4457f662-6716-4b9c-b501-61969330bfa7.mov
=> fix(TypeAheadDropdown): scroll to selected item upon first render

src/Components/Button/Button.scss, src/Components/Button/Composed/DismissButton.scss, src/Components/Button/Composed/LinkButton.scss, src/Styles/variables.scss
Closes https://github.com/influxdata/clockface/issues/836
1. Changes button colors.
=> feat(ButtonBase): clockface 4 colors

src/Styles/variables.scss
Closes [#845](https://github.com/influxdata/clockface/issues/845)
=> feat(EmptyState): Clockface 4 updates

src/Styles/variables.scss
A chore to remove unused color variables. More cleanup coming in the future, we need to map the old colors to the new ones, this is the first step.
=> chore(Clockface 4): remove unused color variables

src/Components/Dropdowns/Dropdown.scss, src/Components/List/List.scss, src/Components/List/ListIndicator.scss, src/Styles/variables.scss
Closes https://github.com/influxdata/clockface/issues/849
=> feat(Clockface 4): List

src/Components/TreeNav/TreeNav.scss
Closes https://github.com/influxdata/clockface/issues/850
=> feat(Clockface 4): TreeNav updates

package.json, yarn.lock
* chore: remove {jest,eslint}/**/ansi-regex resolutions (no longer needed)
* chore: use resolution to resolve minimatch
=> chore: use resolution to resolve minimatch

package.json, yarn.lock
https://github.com/influxdata/clockface/pull/903 missed one. Sorry for the extra PR!
=> chore: add missed resolution for loader-utils 1.4.2
